#!/bin/bash
set -e


AWS_DEFAULT_REGION="ap-northeast-1"

if [ -z $AWS_ACCESS_KEY_ID ] ||
   [ -z $AWS_SECRET_ACCESS_KEY ] ||
   [ -z $AWS_SESSION_TOKEN ]
then
    echo "Please set your credential."
    echo "ex)"
    echo "export AWS_ACCESS_KEY_ID=xxxxx"
    echo "export AWS_SECRET_ACCESS_KEY=xxxxx"
    echo "export AWS_SESSION_TOKEN=xxxx"

    exit -1;
fi


exists_image=$(docker images | grep ekscmd | wc -l)

if [ $exists_image -eq 0 ]
then
    cd docker
    build.sh
    cd -
fi

docker run -ith eks --rm \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
    -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
    -e PATH=/work/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.krew/bin \
    -w /work \
    -v $PWD:/work \
    -v aks_cmd_root:/root \
    -v /var/run/docker.sock:/var/run/docker.sock \
    ekscmd:latest fish
